### ISSUE TITLE
daemonise

### ISSUE THREAD

**Issue by flyingrub** [N07070/Py-Human-Uptime#1]
you could daemonise it with an init.d script :)

**Comment by N07070** [comment]
I shall accept any pull request :)

**Comment by N07070** [comment]
If you prive a tutorial, I shall post it, and close the issue.

**Comment by flyingrub** [comment]
http://blog.scphillips.com/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/
:)
